/*
 * Class: Cellular Automata
 * in here, an LifeLikeCA is represented by a matrix of 128 x 128
 * all the LifeLikeCA can be generated by initilly set a rule
 * all LifeLikeCA has 8 neighbors 
 * Rules example:
 * String []LifeGameType = {"B018/S018","B0578/S045","B0578/S12456","B1/S012345678",
 * "B1/S1","B123567/S0238","B13456/S01356","B135/S135","B1357/S1357","B137/S45678",
 * "B2/S","B234/S","B236/S0468","B257/S27","B3/S012345678","B3/S12345","B3/S23",
 * "B3/S234","B3/S45678","B34/S03456","B34/S34","B345/S4567","B345/S5","B35678/S5678",
 * "B357/S1358","B357/S238","B36/S125","B36/S23","B367/S2346","B3678/S235678",
 * "B3678/S34678","B368/S245","B378/S012345678","B378/S235678","B45678/S2345"};
 * B: birth
 * S: survival
 * -------------------------------------------------------------------------------------------
 * This class can also be extended as a JPanel to make graphic interface,
 * by just adding this class to the BEAN palette. 
 */
package CA.grid;

import java.awt.Color;
import java.awt.Graphics;
import java.io.Serializable;
import java.util.Random;
import javax.swing.JPanel;

public final class LifeLikeCA extends JPanel implements Serializable {

    private int tempo=0;
//    private static final int ROW = 8;
//    private static final int COL = 8;
    public int ROW = 128;
    public int COL = 128;
    public int[][] prevMatrix;
    public int[][] curMatrix;
    private String LifeGameType = "B1357/S2468";//Fredkin // NOTA.. este LifeLikeCA no admite valores de 0, por lo que reglas B1357/S02468 no seria permitido.
    //private String LifeGameType = "B23/S36"; //Game type in Born/Survival notation.// Proposed
    // private String LifeGameType = "B3/S23"; //Conway`s Game of life
    // private String LifeGameType = "B123567/S0238";//Wolfram & Packard Fig. 13(f); class 3
    private float initialProbability = 0.5f; //probability of initial life at pixels.
    
    private boolean useToroidalGrid = true;
    int defaultConstantBorder = 0;
//Born          0 1 2 3 4 5 6 7 8
    int[] Born = {
        0, 0, 0, 0, 0, 0, 0, 0, 0
    };
//Survive       0 1 2 3 4 5 6 7 8
    int[] Survive = {
        0, 0, 0, 0, 0, 0, 0, 0, 0
    };
//Neighbours
    int[] xdirections = {
        -1, 0, 1, -1, 1, -1, 0, 1
    };
    int[] ydirections = {
        -1, -1, -1, 0, 0, 1, 1, 1
    };

    public LifeLikeCA() {
        prevMatrix = new int[ROW][COL];
        curMatrix = new int[ROW][COL];
        parseBornSurvive(LifeGameType);


    }

    public LifeLikeCA(String rule) {
        prevMatrix = new int[ROW][COL];
        curMatrix = new int[ROW][COL];
        LifeGameType = rule;
        parseBornSurvive(LifeGameType);
    }

    public LifeLikeCA(int r, int c) {
        ROW = r;
        COL = c;
        prevMatrix = new int[ROW][COL];
        curMatrix = new int[ROW][COL];
        parseBornSurvive(LifeGameType);


    }

////    public static void main(String[] args) {
////        //  LifeLikeCA automata = new LifeLikeCA();
////        //   automata.random();
////        //  automata.step(5);
////        testDistancias();
////    }

    public int[][] getCurrent() {
        return curMatrix.clone(); // NO USAR EL CLONE !!!
    }

    public void setNewRule(String text) {
        LifeGameType = text; // tiene que quedar la regla fixada
        // reinicio os valores da regra
        Born = new int[9]; // a ZERO
        Survive = new int[9];// a ZERO
        parseBornSurvive(LifeGameType);
    }
    /*
     * Function to read and parse the  Rules
     * rule: B23/S36
     */

    void parseBornSurvive(String rule) {
        int Smode = 1;
        int Bmode = 2;
        int noMode = 0;
        int currentMode = noMode;
        for (int i = 0; i < rule.length(); i++) {
            char curChar = rule.charAt(i);
            if (curChar == 'S' || curChar == 's') {
                currentMode = Smode;
            } else if (curChar == 'B' || curChar == 'b') {
                currentMode = Bmode;
            } else {
                if (currentMode == Smode) {
                    switch (curChar) {
                        case '0':
                            Survive[0] = 1;
                            break;
                        case '1':
                            Survive[1] = 1;
                            break;
                        case '2':
                            Survive[2] = 1;
                            break;
                        case '3':
                            Survive[3] = 1;
                            break;
                        case '4':
                            Survive[4] = 1;
                            break;
                        case '5':
                            Survive[5] = 1;
                            break;
                        case '6':
                            Survive[6] = 1;
                            break;
                        case '7':
                            Survive[7] = 1;
                            break;
                        case '8':
                            Survive[8] = 1;
                            break;
                        default:
                            break;
                    }
                } else if (currentMode == Bmode) {
                    switch (curChar) {
                        case '0':
                            Born[0] = 1;
                            break;
                        case '1':
                            Born[1] = 1;
                            break;
                        case '2':
                            Born[2] = 1;
                            break;
                        case '3':
                            Born[3] = 1;
                            break;
                        case '4':
                            Born[4] = 1;
                            break;
                        case '5':
                            Born[5] = 1;
                            break;
                        case '6':
                            Born[6] = 1;
                            break;
                        case '7':
                            Born[7] = 1;
                            break;
                        case '8':
                            Born[8] = 1;
                            break;
                        default:
                            break;
                    }
                }
            }
        }
    }

    /*
     * Hipertoroidal LifeLikeCA, where all edges from LifeLikeCA are connected
     */
    int toroidalNeighbor(int x, int y) {
        int sum = 0;
        for (int i = 0; i < 8; i++) { //i < 8
            int curX = (x + ROW + xdirections[i]) % ROW;
            int curY = (y + COL + ydirections[i]) % COL;
            //System.out.println("x: " + curX + "  y: " + curY);
            sum += prevMatrix[curX][curY];
        }
        return sum;
    }
    /*
     * Traditionally LifeLikeCA, where the edges are not take in count
     */

    int TraditionalNeighbor(int x, int y, int border) {
        int sum = 0;
        for (int i = 0; i < 8; i++) {
            int curX = x + xdirections[i];
            int curY = y + ydirections[i];
            if (curX < ROW && curX >= 0 && curY < COL && curY >= 0) {
                sum += prevMatrix[curX][curY];
            } else {
                sum += border;
            }
        }
        return sum;
    }

    public int valueAt(int x, int y) {
        return curMatrix[x][y];
    }
    /*/
     * Number of iterations: Time step to evolve LifeLikeCA
     */

    public void step(int days) {
//      executes the continuation of the program
        for (int g = 0; g < days; g++) {
            // printBoard();
            // repaint(); // use in JPanel mode
            runStep();
            copyBoard(prevMatrix, curMatrix);
            //repaint();
        }

    }
    // Runs one iteration

    private void runStep() {
        for (int x = 0; x < ROW; x++) {
            for (int y = 0; y < COL; y++) {
                int theSum;
                if (useToroidalGrid) {//Toroidal mode
                    theSum = toroidalNeighbor(x, y);
                } else {
                    theSum = TraditionalNeighbor(x, y, defaultConstantBorder);
                }
                if (prevMatrix[x][y] == 1) { //==1
                    if (Survive[theSum] > 0) {//1
                        curMatrix[x][y] = 1;
                    } else {
                        curMatrix[x][y] = 0;
                    }
                } else {
                    if (Born[theSum] > 0) {
                        curMatrix[x][y] = 1;
                    } else {
                        curMatrix[x][y] = 0;
                    }
                }
            }
        }
        tempo+=1;
    }

    public void clear() {
        for (int k = 0; k < ROW; k++) {
            for (int m = 0; m < COL; m++) {
                curMatrix[k][m] = 0;
                prevMatrix[k][m]=0;
            }
        }
        tempo=0;
    }
    public int getIterations()
    {
        return tempo;
    }

    public void random() {
        clear();
        Random randGen = new Random(1);
        double random = 0;
        // Initial State:
        for (int i = 0; i < ROW; i++) {
            for (int j = 0; j < COL; j++) {
                random = randGen.nextDouble();
                if (random < initialProbability) {
                    curMatrix[i][j] = 1;
                    prevMatrix[i][j] = 1;
                } else {
                    curMatrix[i][j] = 0;
                    prevMatrix[i][j] = 0;
                }
            }
        }
        repaint();
    }

    public void replica(int f, int c) {
        curMatrix[f][c] = (curMatrix[f][c] == 1 ? 0 : 1);
        prevMatrix[f][c] = curMatrix[f][c];
    }

    public void homogeneo() {
        clear();
        // Initial State:
        for (int i = 0; i < ROW / 2; i++) {
            for (int j = 0; j < COL; j++) {
                curMatrix[i][j] = 1;
                prevMatrix[i][j] = 1;
            }
        }
        for (int i = ROW / 2; i < ROW; i++) {
            for (int j = 0; j < COL; j++) {
                curMatrix[i][j] = 0;
                prevMatrix[i][j] = 0;
            }
        }
        repaint();
    }
    
    public void glider() {
        clear();
        // Initial State:
        //8 x 8       
      /*  curMatrix[3][2] = 1;       
        curMatrix[4][3] = 1;
        curMatrix[5][3] = 1;
        curMatrix[3][4] = 1;
        curMatrix[4][4] = 1;
        
        prevMatrix[3][2] = 1;        
        prevMatrix[4][3] = 1;
        prevMatrix[5][3] = 1;
        prevMatrix[3][4] = 1;
        prevMatrix[4][4] = 1;*/
        /*int f = ROW/2;
        int c = COL/2+1;
        curMatrix[f-2][c-2] = 1;       
        curMatrix[f-1][c-1] = 1;
        curMatrix[f][c] = 1; //medio 4- 5
        curMatrix[f+1][c-1] = 1;
        curMatrix[f+2][c-2] = 1;
        
        prevMatrix[f-2][c-2] = 1;       
        prevMatrix[f-1][c-1] = 1;
        prevMatrix[f][c] = 1; //medio 4- 5
        prevMatrix[f+1][c-1] = 1;
        prevMatrix[f+2][c-2] = 1;*/
        
        int f = ROW/2;
        int c = COL/2+1;  
        curMatrix[f-1][c-1] = 1;
        curMatrix[f][c] = 1; //medio 4- 5
        curMatrix[f+1][c-1] = 1;
          
        prevMatrix[f-1][c-1] = 1;
        prevMatrix[f][c] = 1; //medio 4- 5
        prevMatrix[f+1][c-1] = 1;

        repaint();
    }

    public double countAlive() {
        int contador = 0;
        for (int k = 0; k < ROW; k++) {
            for (int m = 0; m < COL; m++) {
                if (curMatrix[k][m] == 1) {
                    contador++;
                }
            }
        }
        return contador;
    }

    public double percentageAlive() {
        double contador = countAlive();
        return (contador * 100) / (ROW * COL);
    }

    public double entropy() {
        double B = countAlive();
        double N = (ROW * COL) - B;
        double blancos = B / (ROW * COL);
        double negros = 1 - blancos;
        double H = (-1) * ((B * log2(blancos)) + (N * log2(negros)));
        H = H / (ROW * COL); // Normalize
        return H;
    }

    public double log2(double x) {
        return Math.log10(x) / Math.log10(2);
    }

    @Override
    public void paint(Graphics g) {
        if (curMatrix == null) {
            return;
        }
        int x, y;
        int vcell = getHeight() / ROW;
        int hcell = getWidth() / COL;

        g.setColor(Color.white);
        g.fillRect(0, 0, getWidth(), getHeight());

        /*g.setColor(Color.white);
        for (y = 0; y < ROW; y++) {
            g.drawLine(0, y * vcell, getWidth(), y * vcell);
        }
        for (x = 0; x < COL; x++) {
            g.drawLine(x * hcell, 0, x * hcell, getHeight());
        }*/
        g.setColor(Color.black);
        for (x = 0; x < COL; x++) {
            for (y = 0; y < ROW; y++) {
                if (curMatrix[x][y] == 1) { // fill
                    g.fillRect(x * hcell, y * vcell, hcell, vcell);
                }
            }
        }

        g.setColor(Color.black);
        g.drawRect(0, 0, getWidth() - 1, getHeight() - 1);

    }

    public void copyBoard(int[][] dst, int[][] src) {
//      copies all the prevMatrix values to the currBoard values
        //dst = src.clone();
        for (int x = 0; x < ROW; x++) {
            for (int y = 0; y < COL; y++) {
                int temp =  src[x][y];
                dst[x][y] =temp;
            }
        }

    }

    public void loadInit(int[][] src) {
        for (int x = 0; x < ROW; x++) {
            for (int y = 0; y < COL; y++) {
                curMatrix[x][y] = src[x][y];
                prevMatrix[x][y] = src[x][y];
            }
        }
    }

    public void printBoard() {
//      •    ->   living cell
//  a space  ->   dead cell
        for (int a = 0; a < ROW; a++) {
            for (int b = 0; b < COL; b++) {
                if (curMatrix[a][b] == 1) {
                    System.out.print("•");
                } else {
                    System.out.print("_");
                }
            }
            System.out.println("");
        }
        System.out.println("------------------------------------------------------------------------------------------------------------------------");
    }

    public int getRow() {
        return ROW;
    }

    public int getCol() {
        return COL;
    }

    public int[][] getMatrix() {
        return curMatrix;
    }

    public int distanciaHamming(LifeLikeCA sPrima) {
        int contador = 0;
        for (int a = 0; a < ROW; a++) {
            for (int b = 0; b < COL; b++) {
                contador += curMatrix[a][b] ^ sPrima.curMatrix[a][b];
            }
        }
        return contador;
    }

    public static double Lyapunov(int t, int et, int e0) {
        //double lyap = (1 / (double) t) * (Math.log((double) et / (double) e0)/ Math.log(2));
        double lyap = (Math.log((double) et / (double) e0) / Math.log(2));
        //System.out.println(lyap);
        return lyap;
    }

    public static void test1() {
        LifeLikeCA s = new LifeLikeCA(40, 40);
        s.random();

        System.out.println("Alive " + s.percentageAlive() + '%');
        LifeLikeCA sPrima = new LifeLikeCA();
        for (int x = 0; x < s.ROW; x++) {
            for (int y = 0; y < s.COL; y++) {
                sPrima.curMatrix[x][y] = s.curMatrix[x][y];
                sPrima.prevMatrix[x][y] = s.prevMatrix[x][y];
            }
        }
        // que sPrima tenga condiciones iniciales con distancia muy pequenha
        if (sPrima.curMatrix[0][0] == 1) {
            sPrima.curMatrix[0][0] = 0;
            sPrima.prevMatrix[0][0] = 0;
        } else {
            sPrima.curMatrix[0][0] = 1;
            sPrima.prevMatrix[0][0] = 1;
        }
        // calcular Hamming
        //System.out.println("[iter=0] " + s.distanciaHamming(sPrima));
        /// //   int e0 = s.distanciaHamming(sPrima);
        int T = 10; // infinito
        double lyap = 0.0d;
        for (int t = 1; t < T; t++) {
            // iterar
            s.step(1);
            sPrima.step(1);

            /////      int et = s.distanciaHamming(sPrima);
            // System.out.println("[t =" + t + "] " + "Lyap= " + Lyapunov(t, et, e0));
            ///     lyap += Lyapunov(t, et, e0);
        }
        lyap = (1 / (double) T) * lyap;
        System.out.println("Lyap= " + lyap);

    }

    public static void testDistancias() {
        String[] LifeGameType = {"B23/S36", "B36/S125", "B34/S34", "B357/S1358", "B345/S4567", "B378/S235678", "B3/S23", "B3/S45678", "B3678/S34678", "B35678/S5678", "B3/S012345678", "B1357/S02468", "B1/S1", "B36/S23", "B345/S5", "B3/S12345", "B3/S1234", "B368/S245", "B357/S238", "B1357/S1357", "B2/S", "B234/S", "B3678/S235678", "B45678/S2345"};
        int tam = 128;

        for (int i = 0; i < LifeGameType.length; i++) {
            System.out.print(LifeGameType[i]+";");
            LifeLikeCA s = new LifeLikeCA(tam, tam);
            s.setNewRule(LifeGameType[i]);
            s.random();           
            int T = 1000; // infinito
            int et =0;
            double value=0;
            for (int t = 0; t < T-1; t++) {
                int[][] temp = new int[tam][tam];
                //temp = s.getCurrent();
                s.copyBoard(temp,s.curMatrix );
                LifeLikeCA sPrima = new LifeLikeCA(tam, tam);
                s.setNewRule(LifeGameType[i]);
                sPrima.loadInit(temp);

                // iterar
                s.step(1);
                et = s.distanciaHamming(sPrima);
                value = (double)et/(tam*tam);
                System.out.print( value+";");
            }
            System.out.print(value);
            System.out.println();
        }


    }

    public static void test2() {
        int T = 100; // iteraciones
        int muestras = 31; // muestras de diferentes tamanhos de matrices

        System.out.print("data=  [");
        for (int XX = 1; XX < muestras; XX++) {// 32 tamanhos diferentes

            int size = 8 * XX;
            LifeLikeCA automata = new LifeLikeCA(size, size);
            automata.random();

            for (int t = 0; t < T; t++) {
                // iterar
                automata.step(1);
                System.out.print(automata.percentageAlive() + "\t ");
            }
            System.out.println(";");
        }

        System.out.println("];");
        //System.out.println("xlabel('Matrix size');");
        //System.out.println("ylabel('% alive');");
        System.out.println("boxplot(data');");
        System.out.print("set(gca,'xtick',1:" + muestras + ", 'xticklabel',");
        int z = 1, size = 1;
        System.out.print("{");
        for (z = 1; z < muestras; z++) {// 32 tamanhos diferentes
            size = 8 * z;
            //System.out.print("'M "+size+"x"+size+"' ,");
            System.out.print("'" + size + "',");
        }
        size = 8 * z;
        //System.out.println("'M "+size+"x"+size+"' });");
        System.out.println("'" + size + "'});");
    }
    //modelo para SPSS

    public static void test3() {
        int T = 100; // infinito

        for (int XX = 1; XX < 31; XX++) {// 32 tamanhos diferentes

            int size = 8 * XX;
            LifeLikeCA automata = new LifeLikeCA(size, size);
            automata.random();

            for (int t = 0; t < T; t++) {
                // iterar
                automata.step(1);
                System.out.println("M" + size + "x" + size + "\t " + automata.percentageAlive());
            }
        }

    }
    // Analizar entropia dependiendo de su iteracion MODO RANDOM/modo homogeneo
   
}
